module.exports = {
  entities: [],
  keepConnectionAlive: true,
  type: 'mysql',
  host: process.env.DB_HOST,
  port: +process.env.DB_PORT,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  charset: 'utf8mb4',
  subscribers: [],
  migrationsRun: false,
  synchronize: false,
  logging: process.env.APP_STAGE === 'development',
  autoLoadEntities: true,
};
